#!/bin/bash

IMAGE="ghcr.io/ricardobranco777/bugme"

DOCKER=$(command -v docker)
PODMAN=$(command -v podman)

# We need unprivileged user namespaces for rootless containers
if unshare -U true >/dev/null 2>&1; then
	SUDO=
else
	SUDO=${SUDO:-$(command -v sudo)}
fi

# Prefer Podman over Docker since it's daemonless and we're holy
RUNTIME="${RUNTIME:-${PODMAN:-$DOCKER}}"

opts=(
	--cap-drop=ALL
	--read-only
	--rm
	--security-opt=no-new-privileges
	--user "$(id -u):$(id -g)"
)

# Do not use sudo if we're in docker group
if [[ $RUNTIME =~ docker ]]; then
	if id -Gn | grep -qw docker; then
		SUDO=
	fi
	opts+=(--net=host)
fi


if [ "$1" = "--version" ] ; then
	latest=$(curl -s https://api.github.com/repos/ricardobranco777/bugme/tags | jq -Mr '.[0].name')
	if [ "${latest#v}" != "$($SUDO "$RUNTIME" run "${opts[@]}" "$IMAGE" --version | awk '{ print $2 }')" ] ; then
		echo "Latest version available: $latest" >&2
	fi
fi

if [ -n "$SUDO" ]; then
	SUDO="$SUDO --preserve-env=DEBUG"
fi

exec $SUDO "$RUNTIME" run "${opts[@]}" -e DEBUG -v "$HOME/creds.json:$HOME/creds.json:ro,z" "$IMAGE" "$@" -c "$HOME/creds.json"
