#!/bin/sh

DOCKER="${DOCKER:-podman}"
IMAGE="ghcr.io/ricardobranco777/bugme"

if [ "$1" = "--version" ] ; then
	latest=$(curl -s https://api.github.com/repos/ricardobranco777/bugme/tags | jq -Mr '.[0].name')
	if [ "${latest#v}" != "$("$DOCKER" run --rm "$IMAGE" --version | awk '{ print $2 }')" ] ; then
		echo "Latest version available: $latest" >&2
	fi
fi

exec "$DOCKER" run --rm -e DEBUG -v ~/creds.json:/root/creds.json:ro,z "$IMAGE" "$@"
