FROM	python:3.11-alpine

COPY	SUSE_Trust_Root.crt /usr/local/share/ca-certificates/

COPY	requirements.txt /tmp

RUN	pip install --no-cache-dir -r /tmp/requirements.txt && \
	update-ca-certificates

COPY	bugme.py /

ENV	REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["/usr/local/bin/python3", "/bugme.py"]
