FROM	python:3.11-alpine

COPY	SUSE_Trust_Root.crt /usr/local/share/ca-certificates/

RUN	apk --no-cache add tzdata

COPY	requirements.txt /tmp

RUN	pip install --no-cache-dir -r /tmp/requirements.txt && \
	update-ca-certificates

COPY	*.py /

ENV	REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

WORKDIR	/bugme

ENTRYPOINT ["/usr/local/bin/python3", "/bugme.py"]
